### ISSUE TITLE
it's deformed

### ISSUE THREAD

**Issue by salehasadi** [Asymmetrik/ngx-leaflet#164]
hi,
i followed the steps you provided in instructions, there no problem and everything is good but as  i try to render the map it will be deformed like this picture:
![deepinscreenshot_20180529194154](https://user-images.githubusercontent.com/14921568/40668165-0c78adca-6379-11e8-8169-790d75fc1035.png)

could you help me with this please!?
thanks.

**Comment by reblace** [comment]
There's usually two things that cause the map to render incorrectly like this.

First, the leaflet CSS file probably hasn't loaded.
Second, it could be that something is changing the page layout without calling invalidateSize.

To tell if it's the first or second, try resizing the window when it's in that state. If nothing changes, it's almost certainly that you aren't loading the leaflet.css file. Review the part of the tutorial that talks about loading css.

**Comment by salehasadi** [comment]
thank you @reblace that was lack of leaflet.css
i restarted the server and that's working now.
![deepinscreenshot_20180529220346](https://user-images.githubusercontent.com/14921568/40675164-313afd12-638c-11e8-806b-46b10974487e.png)
